dotenv: .env
wallets: 
   from_key: ${PRIVATE_KEY}

dependencies:
   - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remapping:
     - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'